### PR TITLE
Release v2.9.1+rev1

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by imrehg** [comment]
@floion I've built this PR, and tried to run `hostapp-update` to update to itself:

```
[INFO] Switching root partition to LABEL="resin-rootB"....../etc/hostapp-update-hooks.d/99-resin-grub: line 21: /mnt/boot/EFI/BOOT/grub.cfg.new: No such file or directory
Failed to run the new hooks. Running current hooks... 
```

Checking it, on qemu `grub.cfg` is at `/mnt/boot/grub/grub.cfg`, not within the `/mnt/boot/EFI/BOOT` folder. This the hook is incorrect for this device type.

**Comment by floion** [comment]
Thanks for the investigaton @imrehg . We will need a new meta-resin release for this

**Comment by floion** [comment]
Should be fixed by https://github.com/resin-os/meta-resin/pull/932

So we need a new meta-resin release

**Comment by imrehg** [comment]
@floion should close this PR then, since the meta-resin will be updated too, right?

**Comment by floion** [comment]
Will branch from it and create a new release and then close it, yes

**Comment by floion** [comment]
Superseded by https://github.com/resin-os/resin-qemu/pull/80

**Pull request closed without merging**
