### PR TITLE
Enable AutoHat support for Qemu 32 bit images

### PR DESCRIPTION
**Pull request by horia-delicoti**
Connects to resin-os/meta-resin#517
@lifeeth @agherzan

### CODE REVIEW

**Comment by lifeeth** [comment]
@resin-jenkins ok to test

**Comment by horia-delicoti** [comment]
New Pull Request created #36

**Comment by agherzan** [comment]
@horia-delicoti why new PR?

**Comment by horia-delicoti** [comment]
@agherzan Because I created this PR from forked repo and jenkins cannot test PRs from forks.

**Comment by agherzan** [comment]
got it

**Pull request closed without merging**
