### PR TITLE
Enable squashfs

### LINKED ISSUE #87: Squashfs
While the Raspberry PI and similar OS's have SquashFS enabled in the kernel options Resin OS 2.12.5+rev1 Qemu images do not.

```
zcat /proc/config.gz | grep SQUAS
# CONFIG_SQUASHFS is not set
```

For those of use using QEMU applications to develop and test our applications for our hardware platforms it would be useful to have this kernel option enabled.

### PR DESCRIPTION
**Pull request by splitice**
Fixes #87

Signed-off-by: Mathew Heard <mheard@x4b.net>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Hi, can you do 2 changes to this PR please?

1 - Change the git commit log to say something like:

>linux-yocto_%.bbappend - Enable squashfs

And then followed by a comment referencing the issue and a short description why you need it maybe.

2 - Also have an entry in CHANGELOG.md saying something like

> * Enable squashfs support [your name here]

**Comment by splitice** [comment]
I have attempted to do this with re-base however keep hitting errors. You have access to this PR please make the changes you desire and then accept.

**Comment by floion** [comment]
Superseded by https://github.com/resin-os/resin-qemu/pull/93

**Pull request closed without merging**
