### PR TITLE
poky: update submodule from jethro-14.0.1 to jethro-14.0.2

### PR DESCRIPTION
**Pull request by fboudra**
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

### CODE REVIEW

**Comment by fboudra** [comment]
@agherzan @willnewton dependency for https://github.com/resin-os/meta-resin/pull/629

**Comment by agherzan** [comment]
@willnewton already pushed a morty update. Wouldn't that fix this issue?

**Comment by fboudra** [comment]
@agherzan I haven't tried with Will's PR for Morty. I just tried a less intrusive change to confirm we need a newer kernel-arch.bbclass. If you're fine with the upgrade from Jethro to Morty, that works for me. Sugar on top, we can get QEMU Aarch64 by moving to Morty.

**Comment by agherzan** [comment]
I thinking moving to morty is a better long term fix. So I'd say we should go that way.

**Comment by willnewton** [comment]
The poky submodule has been upgraded to morty.

**Pull request closed without merging**
